# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/x/DefyX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/x/DefyX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/x/DefyX/CMakeFiles /root/x/DefyX/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/x/DefyX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named defyx

# Build rule for target.
defyx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 defyx
.PHONY : defyx

# fast build rule for target.
defyx/fast:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/build
.PHONY : defyx/fast

#=============================================================================
# Target rules for targets named DefyX-tests

# Build rule for target.
DefyX-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DefyX-tests
.PHONY : DefyX-tests

# fast build rule for target.
DefyX-tests/fast:
	$(MAKE) -f CMakeFiles/DefyX-tests.dir/build.make CMakeFiles/DefyX-tests.dir/build
.PHONY : DefyX-tests/fast

#=============================================================================
# Target rules for targets named defyx-codegen

# Build rule for target.
defyx-codegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 defyx-codegen
.PHONY : defyx-codegen

# fast build rule for target.
defyx-codegen/fast:
	$(MAKE) -f CMakeFiles/defyx-codegen.dir/build.make CMakeFiles/defyx-codegen.dir/build
.PHONY : defyx-codegen/fast

#=============================================================================
# Target rules for targets named defyx-benchmark

# Build rule for target.
defyx-benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 defyx-benchmark
.PHONY : defyx-benchmark

# fast build rule for target.
defyx-benchmark/fast:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/build
.PHONY : defyx-benchmark/fast

src/aes_hash.o: src/aes_hash.cpp.o

.PHONY : src/aes_hash.o

# target to build an object file
src/aes_hash.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/aes_hash.cpp.o
.PHONY : src/aes_hash.cpp.o

src/aes_hash.i: src/aes_hash.cpp.i

.PHONY : src/aes_hash.i

# target to preprocess a source file
src/aes_hash.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/aes_hash.cpp.i
.PHONY : src/aes_hash.cpp.i

src/aes_hash.s: src/aes_hash.cpp.s

.PHONY : src/aes_hash.s

# target to generate assembly for a file
src/aes_hash.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/aes_hash.cpp.s
.PHONY : src/aes_hash.cpp.s

src/allocator.o: src/allocator.cpp.o

.PHONY : src/allocator.o

# target to build an object file
src/allocator.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/allocator.cpp.o
.PHONY : src/allocator.cpp.o

src/allocator.i: src/allocator.cpp.i

.PHONY : src/allocator.i

# target to preprocess a source file
src/allocator.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/allocator.cpp.i
.PHONY : src/allocator.cpp.i

src/allocator.s: src/allocator.cpp.s

.PHONY : src/allocator.s

# target to generate assembly for a file
src/allocator.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/allocator.cpp.s
.PHONY : src/allocator.cpp.s

src/argon2_core.o: src/argon2_core.c.o

.PHONY : src/argon2_core.o

# target to build an object file
src/argon2_core.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_core.c.o
.PHONY : src/argon2_core.c.o

src/argon2_core.i: src/argon2_core.c.i

.PHONY : src/argon2_core.i

# target to preprocess a source file
src/argon2_core.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_core.c.i
.PHONY : src/argon2_core.c.i

src/argon2_core.s: src/argon2_core.c.s

.PHONY : src/argon2_core.s

# target to generate assembly for a file
src/argon2_core.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_core.c.s
.PHONY : src/argon2_core.c.s

src/argon2_ref.o: src/argon2_ref.c.o

.PHONY : src/argon2_ref.o

# target to build an object file
src/argon2_ref.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_ref.c.o
.PHONY : src/argon2_ref.c.o

src/argon2_ref.i: src/argon2_ref.c.i

.PHONY : src/argon2_ref.i

# target to preprocess a source file
src/argon2_ref.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_ref.c.i
.PHONY : src/argon2_ref.c.i

src/argon2_ref.s: src/argon2_ref.c.s

.PHONY : src/argon2_ref.s

# target to generate assembly for a file
src/argon2_ref.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/argon2_ref.c.s
.PHONY : src/argon2_ref.c.s

src/assembly_generator_x86.o: src/assembly_generator_x86.cpp.o

.PHONY : src/assembly_generator_x86.o

# target to build an object file
src/assembly_generator_x86.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/assembly_generator_x86.cpp.o
.PHONY : src/assembly_generator_x86.cpp.o

src/assembly_generator_x86.i: src/assembly_generator_x86.cpp.i

.PHONY : src/assembly_generator_x86.i

# target to preprocess a source file
src/assembly_generator_x86.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/assembly_generator_x86.cpp.i
.PHONY : src/assembly_generator_x86.cpp.i

src/assembly_generator_x86.s: src/assembly_generator_x86.cpp.s

.PHONY : src/assembly_generator_x86.s

# target to generate assembly for a file
src/assembly_generator_x86.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/assembly_generator_x86.cpp.s
.PHONY : src/assembly_generator_x86.cpp.s

src/blake2/KangarooTwelve.o: src/blake2/KangarooTwelve.c.o

.PHONY : src/blake2/KangarooTwelve.o

# target to build an object file
src/blake2/KangarooTwelve.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KangarooTwelve.c.o
.PHONY : src/blake2/KangarooTwelve.c.o

src/blake2/KangarooTwelve.i: src/blake2/KangarooTwelve.c.i

.PHONY : src/blake2/KangarooTwelve.i

# target to preprocess a source file
src/blake2/KangarooTwelve.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KangarooTwelve.c.i
.PHONY : src/blake2/KangarooTwelve.c.i

src/blake2/KangarooTwelve.s: src/blake2/KangarooTwelve.c.s

.PHONY : src/blake2/KangarooTwelve.s

# target to generate assembly for a file
src/blake2/KangarooTwelve.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KangarooTwelve.c.s
.PHONY : src/blake2/KangarooTwelve.c.s

src/blake2/KeccakP-1600-reference.o: src/blake2/KeccakP-1600-reference.c.o

.PHONY : src/blake2/KeccakP-1600-reference.o

# target to build an object file
src/blake2/KeccakP-1600-reference.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakP-1600-reference.c.o
.PHONY : src/blake2/KeccakP-1600-reference.c.o

src/blake2/KeccakP-1600-reference.i: src/blake2/KeccakP-1600-reference.c.i

.PHONY : src/blake2/KeccakP-1600-reference.i

# target to preprocess a source file
src/blake2/KeccakP-1600-reference.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakP-1600-reference.c.i
.PHONY : src/blake2/KeccakP-1600-reference.c.i

src/blake2/KeccakP-1600-reference.s: src/blake2/KeccakP-1600-reference.c.s

.PHONY : src/blake2/KeccakP-1600-reference.s

# target to generate assembly for a file
src/blake2/KeccakP-1600-reference.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakP-1600-reference.c.s
.PHONY : src/blake2/KeccakP-1600-reference.c.s

src/blake2/KeccakSpongeWidth1600.o: src/blake2/KeccakSpongeWidth1600.c.o

.PHONY : src/blake2/KeccakSpongeWidth1600.o

# target to build an object file
src/blake2/KeccakSpongeWidth1600.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakSpongeWidth1600.c.o
.PHONY : src/blake2/KeccakSpongeWidth1600.c.o

src/blake2/KeccakSpongeWidth1600.i: src/blake2/KeccakSpongeWidth1600.c.i

.PHONY : src/blake2/KeccakSpongeWidth1600.i

# target to preprocess a source file
src/blake2/KeccakSpongeWidth1600.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakSpongeWidth1600.c.i
.PHONY : src/blake2/KeccakSpongeWidth1600.c.i

src/blake2/KeccakSpongeWidth1600.s: src/blake2/KeccakSpongeWidth1600.c.s

.PHONY : src/blake2/KeccakSpongeWidth1600.s

# target to generate assembly for a file
src/blake2/KeccakSpongeWidth1600.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/KeccakSpongeWidth1600.c.s
.PHONY : src/blake2/KeccakSpongeWidth1600.c.s

src/blake2/blake2b.o: src/blake2/blake2b.c.o

.PHONY : src/blake2/blake2b.o

# target to build an object file
src/blake2/blake2b.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/blake2b.c.o
.PHONY : src/blake2/blake2b.c.o

src/blake2/blake2b.i: src/blake2/blake2b.c.i

.PHONY : src/blake2/blake2b.i

# target to preprocess a source file
src/blake2/blake2b.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/blake2b.c.i
.PHONY : src/blake2/blake2b.c.i

src/blake2/blake2b.s: src/blake2/blake2b.c.s

.PHONY : src/blake2/blake2b.s

# target to generate assembly for a file
src/blake2/blake2b.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/blake2b.c.s
.PHONY : src/blake2/blake2b.c.s

src/blake2/sha256.o: src/blake2/sha256.c.o

.PHONY : src/blake2/sha256.o

# target to build an object file
src/blake2/sha256.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/sha256.c.o
.PHONY : src/blake2/sha256.c.o

src/blake2/sha256.i: src/blake2/sha256.c.i

.PHONY : src/blake2/sha256.i

# target to preprocess a source file
src/blake2/sha256.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/sha256.c.i
.PHONY : src/blake2/sha256.c.i

src/blake2/sha256.s: src/blake2/sha256.c.s

.PHONY : src/blake2/sha256.s

# target to generate assembly for a file
src/blake2/sha256.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/sha256.c.s
.PHONY : src/blake2/sha256.c.s

src/blake2/yescrypt-best.o: src/blake2/yescrypt-best.c.o

.PHONY : src/blake2/yescrypt-best.o

# target to build an object file
src/blake2/yescrypt-best.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-best.c.o
.PHONY : src/blake2/yescrypt-best.c.o

src/blake2/yescrypt-best.i: src/blake2/yescrypt-best.c.i

.PHONY : src/blake2/yescrypt-best.i

# target to preprocess a source file
src/blake2/yescrypt-best.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-best.c.i
.PHONY : src/blake2/yescrypt-best.c.i

src/blake2/yescrypt-best.s: src/blake2/yescrypt-best.c.s

.PHONY : src/blake2/yescrypt-best.s

# target to generate assembly for a file
src/blake2/yescrypt-best.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-best.c.s
.PHONY : src/blake2/yescrypt-best.c.s

src/blake2/yescrypt-common.o: src/blake2/yescrypt-common.c.o

.PHONY : src/blake2/yescrypt-common.o

# target to build an object file
src/blake2/yescrypt-common.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-common.c.o
.PHONY : src/blake2/yescrypt-common.c.o

src/blake2/yescrypt-common.i: src/blake2/yescrypt-common.c.i

.PHONY : src/blake2/yescrypt-common.i

# target to preprocess a source file
src/blake2/yescrypt-common.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-common.c.i
.PHONY : src/blake2/yescrypt-common.c.i

src/blake2/yescrypt-common.s: src/blake2/yescrypt-common.c.s

.PHONY : src/blake2/yescrypt-common.s

# target to generate assembly for a file
src/blake2/yescrypt-common.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-common.c.s
.PHONY : src/blake2/yescrypt-common.c.s

src/blake2/yescrypt-opt.o: src/blake2/yescrypt-opt.c.o

.PHONY : src/blake2/yescrypt-opt.o

# target to build an object file
src/blake2/yescrypt-opt.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-opt.c.o
.PHONY : src/blake2/yescrypt-opt.c.o

src/blake2/yescrypt-opt.i: src/blake2/yescrypt-opt.c.i

.PHONY : src/blake2/yescrypt-opt.i

# target to preprocess a source file
src/blake2/yescrypt-opt.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-opt.c.i
.PHONY : src/blake2/yescrypt-opt.c.i

src/blake2/yescrypt-opt.s: src/blake2/yescrypt-opt.c.s

.PHONY : src/blake2/yescrypt-opt.s

# target to generate assembly for a file
src/blake2/yescrypt-opt.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-opt.c.s
.PHONY : src/blake2/yescrypt-opt.c.s

src/blake2/yescrypt-platform.o: src/blake2/yescrypt-platform.c.o

.PHONY : src/blake2/yescrypt-platform.o

# target to build an object file
src/blake2/yescrypt-platform.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-platform.c.o
.PHONY : src/blake2/yescrypt-platform.c.o

src/blake2/yescrypt-platform.i: src/blake2/yescrypt-platform.c.i

.PHONY : src/blake2/yescrypt-platform.i

# target to preprocess a source file
src/blake2/yescrypt-platform.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-platform.c.i
.PHONY : src/blake2/yescrypt-platform.c.i

src/blake2/yescrypt-platform.s: src/blake2/yescrypt-platform.c.s

.PHONY : src/blake2/yescrypt-platform.s

# target to generate assembly for a file
src/blake2/yescrypt-platform.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-platform.c.s
.PHONY : src/blake2/yescrypt-platform.c.s

src/blake2/yescrypt-ref.o: src/blake2/yescrypt-ref.c.o

.PHONY : src/blake2/yescrypt-ref.o

# target to build an object file
src/blake2/yescrypt-ref.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-ref.c.o
.PHONY : src/blake2/yescrypt-ref.c.o

src/blake2/yescrypt-ref.i: src/blake2/yescrypt-ref.c.i

.PHONY : src/blake2/yescrypt-ref.i

# target to preprocess a source file
src/blake2/yescrypt-ref.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-ref.c.i
.PHONY : src/blake2/yescrypt-ref.c.i

src/blake2/yescrypt-ref.s: src/blake2/yescrypt-ref.c.s

.PHONY : src/blake2/yescrypt-ref.s

# target to generate assembly for a file
src/blake2/yescrypt-ref.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-ref.c.s
.PHONY : src/blake2/yescrypt-ref.c.s

src/blake2/yescrypt-simd.o: src/blake2/yescrypt-simd.c.o

.PHONY : src/blake2/yescrypt-simd.o

# target to build an object file
src/blake2/yescrypt-simd.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-simd.c.o
.PHONY : src/blake2/yescrypt-simd.c.o

src/blake2/yescrypt-simd.i: src/blake2/yescrypt-simd.c.i

.PHONY : src/blake2/yescrypt-simd.i

# target to preprocess a source file
src/blake2/yescrypt-simd.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-simd.c.i
.PHONY : src/blake2/yescrypt-simd.c.i

src/blake2/yescrypt-simd.s: src/blake2/yescrypt-simd.c.s

.PHONY : src/blake2/yescrypt-simd.s

# target to generate assembly for a file
src/blake2/yescrypt-simd.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2/yescrypt-simd.c.s
.PHONY : src/blake2/yescrypt-simd.c.s

src/blake2_generator.o: src/blake2_generator.cpp.o

.PHONY : src/blake2_generator.o

# target to build an object file
src/blake2_generator.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2_generator.cpp.o
.PHONY : src/blake2_generator.cpp.o

src/blake2_generator.i: src/blake2_generator.cpp.i

.PHONY : src/blake2_generator.i

# target to preprocess a source file
src/blake2_generator.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2_generator.cpp.i
.PHONY : src/blake2_generator.cpp.i

src/blake2_generator.s: src/blake2_generator.cpp.s

.PHONY : src/blake2_generator.s

# target to generate assembly for a file
src/blake2_generator.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/blake2_generator.cpp.s
.PHONY : src/blake2_generator.cpp.s

src/bytecode_machine.o: src/bytecode_machine.cpp.o

.PHONY : src/bytecode_machine.o

# target to build an object file
src/bytecode_machine.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/bytecode_machine.cpp.o
.PHONY : src/bytecode_machine.cpp.o

src/bytecode_machine.i: src/bytecode_machine.cpp.i

.PHONY : src/bytecode_machine.i

# target to preprocess a source file
src/bytecode_machine.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/bytecode_machine.cpp.i
.PHONY : src/bytecode_machine.cpp.i

src/bytecode_machine.s: src/bytecode_machine.cpp.s

.PHONY : src/bytecode_machine.s

# target to generate assembly for a file
src/bytecode_machine.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/bytecode_machine.cpp.s
.PHONY : src/bytecode_machine.cpp.s

src/dataset.o: src/dataset.cpp.o

.PHONY : src/dataset.o

# target to build an object file
src/dataset.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/dataset.cpp.o
.PHONY : src/dataset.cpp.o

src/dataset.i: src/dataset.cpp.i

.PHONY : src/dataset.i

# target to preprocess a source file
src/dataset.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/dataset.cpp.i
.PHONY : src/dataset.cpp.i

src/dataset.s: src/dataset.cpp.s

.PHONY : src/dataset.s

# target to generate assembly for a file
src/dataset.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/dataset.cpp.s
.PHONY : src/dataset.cpp.s

src/defyx.o: src/defyx.cpp.o

.PHONY : src/defyx.o

# target to build an object file
src/defyx.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/defyx.cpp.o
.PHONY : src/defyx.cpp.o

src/defyx.i: src/defyx.cpp.i

.PHONY : src/defyx.i

# target to preprocess a source file
src/defyx.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/defyx.cpp.i
.PHONY : src/defyx.cpp.i

src/defyx.s: src/defyx.cpp.s

.PHONY : src/defyx.s

# target to generate assembly for a file
src/defyx.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/defyx.cpp.s
.PHONY : src/defyx.cpp.s

src/instruction.o: src/instruction.cpp.o

.PHONY : src/instruction.o

# target to build an object file
src/instruction.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instruction.cpp.o
.PHONY : src/instruction.cpp.o

src/instruction.i: src/instruction.cpp.i

.PHONY : src/instruction.i

# target to preprocess a source file
src/instruction.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instruction.cpp.i
.PHONY : src/instruction.cpp.i

src/instruction.s: src/instruction.cpp.s

.PHONY : src/instruction.s

# target to generate assembly for a file
src/instruction.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instruction.cpp.s
.PHONY : src/instruction.cpp.s

src/instructions_portable.o: src/instructions_portable.cpp.o

.PHONY : src/instructions_portable.o

# target to build an object file
src/instructions_portable.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instructions_portable.cpp.o
.PHONY : src/instructions_portable.cpp.o

src/instructions_portable.i: src/instructions_portable.cpp.i

.PHONY : src/instructions_portable.i

# target to preprocess a source file
src/instructions_portable.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instructions_portable.cpp.i
.PHONY : src/instructions_portable.cpp.i

src/instructions_portable.s: src/instructions_portable.cpp.s

.PHONY : src/instructions_portable.s

# target to generate assembly for a file
src/instructions_portable.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/instructions_portable.cpp.s
.PHONY : src/instructions_portable.cpp.s

src/jit_compiler_x86.o: src/jit_compiler_x86.cpp.o

.PHONY : src/jit_compiler_x86.o

# target to build an object file
src/jit_compiler_x86.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86.cpp.o
.PHONY : src/jit_compiler_x86.cpp.o

src/jit_compiler_x86.i: src/jit_compiler_x86.cpp.i

.PHONY : src/jit_compiler_x86.i

# target to preprocess a source file
src/jit_compiler_x86.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86.cpp.i
.PHONY : src/jit_compiler_x86.cpp.i

src/jit_compiler_x86.s: src/jit_compiler_x86.cpp.s

.PHONY : src/jit_compiler_x86.s

# target to generate assembly for a file
src/jit_compiler_x86.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86.cpp.s
.PHONY : src/jit_compiler_x86.cpp.s

src/jit_compiler_x86_static.o: src/jit_compiler_x86_static.S.o

.PHONY : src/jit_compiler_x86_static.o

# target to build an object file
src/jit_compiler_x86_static.S.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86_static.S.o
.PHONY : src/jit_compiler_x86_static.S.o

src/jit_compiler_x86_static.i: src/jit_compiler_x86_static.S.i

.PHONY : src/jit_compiler_x86_static.i

# target to preprocess a source file
src/jit_compiler_x86_static.S.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86_static.S.i
.PHONY : src/jit_compiler_x86_static.S.i

src/jit_compiler_x86_static.s: src/jit_compiler_x86_static.S.s

.PHONY : src/jit_compiler_x86_static.s

# target to generate assembly for a file
src/jit_compiler_x86_static.S.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/jit_compiler_x86_static.S.s
.PHONY : src/jit_compiler_x86_static.S.s

src/reciprocal.o: src/reciprocal.c.o

.PHONY : src/reciprocal.o

# target to build an object file
src/reciprocal.c.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/reciprocal.c.o
.PHONY : src/reciprocal.c.o

src/reciprocal.i: src/reciprocal.c.i

.PHONY : src/reciprocal.i

# target to preprocess a source file
src/reciprocal.c.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/reciprocal.c.i
.PHONY : src/reciprocal.c.i

src/reciprocal.s: src/reciprocal.c.s

.PHONY : src/reciprocal.s

# target to generate assembly for a file
src/reciprocal.c.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/reciprocal.c.s
.PHONY : src/reciprocal.c.s

src/soft_aes.o: src/soft_aes.cpp.o

.PHONY : src/soft_aes.o

# target to build an object file
src/soft_aes.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/soft_aes.cpp.o
.PHONY : src/soft_aes.cpp.o

src/soft_aes.i: src/soft_aes.cpp.i

.PHONY : src/soft_aes.i

# target to preprocess a source file
src/soft_aes.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/soft_aes.cpp.i
.PHONY : src/soft_aes.cpp.i

src/soft_aes.s: src/soft_aes.cpp.s

.PHONY : src/soft_aes.s

# target to generate assembly for a file
src/soft_aes.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/soft_aes.cpp.s
.PHONY : src/soft_aes.cpp.s

src/superscalar.o: src/superscalar.cpp.o

.PHONY : src/superscalar.o

# target to build an object file
src/superscalar.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/superscalar.cpp.o
.PHONY : src/superscalar.cpp.o

src/superscalar.i: src/superscalar.cpp.i

.PHONY : src/superscalar.i

# target to preprocess a source file
src/superscalar.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/superscalar.cpp.i
.PHONY : src/superscalar.cpp.i

src/superscalar.s: src/superscalar.cpp.s

.PHONY : src/superscalar.s

# target to generate assembly for a file
src/superscalar.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/superscalar.cpp.s
.PHONY : src/superscalar.cpp.s

src/tests/affinity.o: src/tests/affinity.cpp.o

.PHONY : src/tests/affinity.o

# target to build an object file
src/tests/affinity.cpp.o:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/affinity.cpp.o
.PHONY : src/tests/affinity.cpp.o

src/tests/affinity.i: src/tests/affinity.cpp.i

.PHONY : src/tests/affinity.i

# target to preprocess a source file
src/tests/affinity.cpp.i:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/affinity.cpp.i
.PHONY : src/tests/affinity.cpp.i

src/tests/affinity.s: src/tests/affinity.cpp.s

.PHONY : src/tests/affinity.s

# target to generate assembly for a file
src/tests/affinity.cpp.s:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/affinity.cpp.s
.PHONY : src/tests/affinity.cpp.s

src/tests/benchmark.o: src/tests/benchmark.cpp.o

.PHONY : src/tests/benchmark.o

# target to build an object file
src/tests/benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/benchmark.cpp.o
.PHONY : src/tests/benchmark.cpp.o

src/tests/benchmark.i: src/tests/benchmark.cpp.i

.PHONY : src/tests/benchmark.i

# target to preprocess a source file
src/tests/benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/benchmark.cpp.i
.PHONY : src/tests/benchmark.cpp.i

src/tests/benchmark.s: src/tests/benchmark.cpp.s

.PHONY : src/tests/benchmark.s

# target to generate assembly for a file
src/tests/benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/defyx-benchmark.dir/build.make CMakeFiles/defyx-benchmark.dir/src/tests/benchmark.cpp.s
.PHONY : src/tests/benchmark.cpp.s

src/tests/code-generator.o: src/tests/code-generator.cpp.o

.PHONY : src/tests/code-generator.o

# target to build an object file
src/tests/code-generator.cpp.o:
	$(MAKE) -f CMakeFiles/defyx-codegen.dir/build.make CMakeFiles/defyx-codegen.dir/src/tests/code-generator.cpp.o
.PHONY : src/tests/code-generator.cpp.o

src/tests/code-generator.i: src/tests/code-generator.cpp.i

.PHONY : src/tests/code-generator.i

# target to preprocess a source file
src/tests/code-generator.cpp.i:
	$(MAKE) -f CMakeFiles/defyx-codegen.dir/build.make CMakeFiles/defyx-codegen.dir/src/tests/code-generator.cpp.i
.PHONY : src/tests/code-generator.cpp.i

src/tests/code-generator.s: src/tests/code-generator.cpp.s

.PHONY : src/tests/code-generator.s

# target to generate assembly for a file
src/tests/code-generator.cpp.s:
	$(MAKE) -f CMakeFiles/defyx-codegen.dir/build.make CMakeFiles/defyx-codegen.dir/src/tests/code-generator.cpp.s
.PHONY : src/tests/code-generator.cpp.s

src/tests/tests.o: src/tests/tests.cpp.o

.PHONY : src/tests/tests.o

# target to build an object file
src/tests/tests.cpp.o:
	$(MAKE) -f CMakeFiles/DefyX-tests.dir/build.make CMakeFiles/DefyX-tests.dir/src/tests/tests.cpp.o
.PHONY : src/tests/tests.cpp.o

src/tests/tests.i: src/tests/tests.cpp.i

.PHONY : src/tests/tests.i

# target to preprocess a source file
src/tests/tests.cpp.i:
	$(MAKE) -f CMakeFiles/DefyX-tests.dir/build.make CMakeFiles/DefyX-tests.dir/src/tests/tests.cpp.i
.PHONY : src/tests/tests.cpp.i

src/tests/tests.s: src/tests/tests.cpp.s

.PHONY : src/tests/tests.s

# target to generate assembly for a file
src/tests/tests.cpp.s:
	$(MAKE) -f CMakeFiles/DefyX-tests.dir/build.make CMakeFiles/DefyX-tests.dir/src/tests/tests.cpp.s
.PHONY : src/tests/tests.cpp.s

src/virtual_machine.o: src/virtual_machine.cpp.o

.PHONY : src/virtual_machine.o

# target to build an object file
src/virtual_machine.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_machine.cpp.o
.PHONY : src/virtual_machine.cpp.o

src/virtual_machine.i: src/virtual_machine.cpp.i

.PHONY : src/virtual_machine.i

# target to preprocess a source file
src/virtual_machine.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_machine.cpp.i
.PHONY : src/virtual_machine.cpp.i

src/virtual_machine.s: src/virtual_machine.cpp.s

.PHONY : src/virtual_machine.s

# target to generate assembly for a file
src/virtual_machine.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_machine.cpp.s
.PHONY : src/virtual_machine.cpp.s

src/virtual_memory.o: src/virtual_memory.cpp.o

.PHONY : src/virtual_memory.o

# target to build an object file
src/virtual_memory.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_memory.cpp.o
.PHONY : src/virtual_memory.cpp.o

src/virtual_memory.i: src/virtual_memory.cpp.i

.PHONY : src/virtual_memory.i

# target to preprocess a source file
src/virtual_memory.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_memory.cpp.i
.PHONY : src/virtual_memory.cpp.i

src/virtual_memory.s: src/virtual_memory.cpp.s

.PHONY : src/virtual_memory.s

# target to generate assembly for a file
src/virtual_memory.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/virtual_memory.cpp.s
.PHONY : src/virtual_memory.cpp.s

src/vm_compiled.o: src/vm_compiled.cpp.o

.PHONY : src/vm_compiled.o

# target to build an object file
src/vm_compiled.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled.cpp.o
.PHONY : src/vm_compiled.cpp.o

src/vm_compiled.i: src/vm_compiled.cpp.i

.PHONY : src/vm_compiled.i

# target to preprocess a source file
src/vm_compiled.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled.cpp.i
.PHONY : src/vm_compiled.cpp.i

src/vm_compiled.s: src/vm_compiled.cpp.s

.PHONY : src/vm_compiled.s

# target to generate assembly for a file
src/vm_compiled.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled.cpp.s
.PHONY : src/vm_compiled.cpp.s

src/vm_compiled_light.o: src/vm_compiled_light.cpp.o

.PHONY : src/vm_compiled_light.o

# target to build an object file
src/vm_compiled_light.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled_light.cpp.o
.PHONY : src/vm_compiled_light.cpp.o

src/vm_compiled_light.i: src/vm_compiled_light.cpp.i

.PHONY : src/vm_compiled_light.i

# target to preprocess a source file
src/vm_compiled_light.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled_light.cpp.i
.PHONY : src/vm_compiled_light.cpp.i

src/vm_compiled_light.s: src/vm_compiled_light.cpp.s

.PHONY : src/vm_compiled_light.s

# target to generate assembly for a file
src/vm_compiled_light.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_compiled_light.cpp.s
.PHONY : src/vm_compiled_light.cpp.s

src/vm_interpreted.o: src/vm_interpreted.cpp.o

.PHONY : src/vm_interpreted.o

# target to build an object file
src/vm_interpreted.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted.cpp.o
.PHONY : src/vm_interpreted.cpp.o

src/vm_interpreted.i: src/vm_interpreted.cpp.i

.PHONY : src/vm_interpreted.i

# target to preprocess a source file
src/vm_interpreted.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted.cpp.i
.PHONY : src/vm_interpreted.cpp.i

src/vm_interpreted.s: src/vm_interpreted.cpp.s

.PHONY : src/vm_interpreted.s

# target to generate assembly for a file
src/vm_interpreted.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted.cpp.s
.PHONY : src/vm_interpreted.cpp.s

src/vm_interpreted_light.o: src/vm_interpreted_light.cpp.o

.PHONY : src/vm_interpreted_light.o

# target to build an object file
src/vm_interpreted_light.cpp.o:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted_light.cpp.o
.PHONY : src/vm_interpreted_light.cpp.o

src/vm_interpreted_light.i: src/vm_interpreted_light.cpp.i

.PHONY : src/vm_interpreted_light.i

# target to preprocess a source file
src/vm_interpreted_light.cpp.i:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted_light.cpp.i
.PHONY : src/vm_interpreted_light.cpp.i

src/vm_interpreted_light.s: src/vm_interpreted_light.cpp.s

.PHONY : src/vm_interpreted_light.s

# target to generate assembly for a file
src/vm_interpreted_light.cpp.s:
	$(MAKE) -f CMakeFiles/defyx.dir/build.make CMakeFiles/defyx.dir/src/vm_interpreted_light.cpp.s
.PHONY : src/vm_interpreted_light.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... defyx"
	@echo "... DefyX-tests"
	@echo "... defyx-codegen"
	@echo "... defyx-benchmark"
	@echo "... src/aes_hash.o"
	@echo "... src/aes_hash.i"
	@echo "... src/aes_hash.s"
	@echo "... src/allocator.o"
	@echo "... src/allocator.i"
	@echo "... src/allocator.s"
	@echo "... src/argon2_core.o"
	@echo "... src/argon2_core.i"
	@echo "... src/argon2_core.s"
	@echo "... src/argon2_ref.o"
	@echo "... src/argon2_ref.i"
	@echo "... src/argon2_ref.s"
	@echo "... src/assembly_generator_x86.o"
	@echo "... src/assembly_generator_x86.i"
	@echo "... src/assembly_generator_x86.s"
	@echo "... src/blake2/KangarooTwelve.o"
	@echo "... src/blake2/KangarooTwelve.i"
	@echo "... src/blake2/KangarooTwelve.s"
	@echo "... src/blake2/KeccakP-1600-reference.o"
	@echo "... src/blake2/KeccakP-1600-reference.i"
	@echo "... src/blake2/KeccakP-1600-reference.s"
	@echo "... src/blake2/KeccakSpongeWidth1600.o"
	@echo "... src/blake2/KeccakSpongeWidth1600.i"
	@echo "... src/blake2/KeccakSpongeWidth1600.s"
	@echo "... src/blake2/blake2b.o"
	@echo "... src/blake2/blake2b.i"
	@echo "... src/blake2/blake2b.s"
	@echo "... src/blake2/sha256.o"
	@echo "... src/blake2/sha256.i"
	@echo "... src/blake2/sha256.s"
	@echo "... src/blake2/yescrypt-best.o"
	@echo "... src/blake2/yescrypt-best.i"
	@echo "... src/blake2/yescrypt-best.s"
	@echo "... src/blake2/yescrypt-common.o"
	@echo "... src/blake2/yescrypt-common.i"
	@echo "... src/blake2/yescrypt-common.s"
	@echo "... src/blake2/yescrypt-opt.o"
	@echo "... src/blake2/yescrypt-opt.i"
	@echo "... src/blake2/yescrypt-opt.s"
	@echo "... src/blake2/yescrypt-platform.o"
	@echo "... src/blake2/yescrypt-platform.i"
	@echo "... src/blake2/yescrypt-platform.s"
	@echo "... src/blake2/yescrypt-ref.o"
	@echo "... src/blake2/yescrypt-ref.i"
	@echo "... src/blake2/yescrypt-ref.s"
	@echo "... src/blake2/yescrypt-simd.o"
	@echo "... src/blake2/yescrypt-simd.i"
	@echo "... src/blake2/yescrypt-simd.s"
	@echo "... src/blake2_generator.o"
	@echo "... src/blake2_generator.i"
	@echo "... src/blake2_generator.s"
	@echo "... src/bytecode_machine.o"
	@echo "... src/bytecode_machine.i"
	@echo "... src/bytecode_machine.s"
	@echo "... src/dataset.o"
	@echo "... src/dataset.i"
	@echo "... src/dataset.s"
	@echo "... src/defyx.o"
	@echo "... src/defyx.i"
	@echo "... src/defyx.s"
	@echo "... src/instruction.o"
	@echo "... src/instruction.i"
	@echo "... src/instruction.s"
	@echo "... src/instructions_portable.o"
	@echo "... src/instructions_portable.i"
	@echo "... src/instructions_portable.s"
	@echo "... src/jit_compiler_x86.o"
	@echo "... src/jit_compiler_x86.i"
	@echo "... src/jit_compiler_x86.s"
	@echo "... src/jit_compiler_x86_static.o"
	@echo "... src/jit_compiler_x86_static.i"
	@echo "... src/jit_compiler_x86_static.s"
	@echo "... src/reciprocal.o"
	@echo "... src/reciprocal.i"
	@echo "... src/reciprocal.s"
	@echo "... src/soft_aes.o"
	@echo "... src/soft_aes.i"
	@echo "... src/soft_aes.s"
	@echo "... src/superscalar.o"
	@echo "... src/superscalar.i"
	@echo "... src/superscalar.s"
	@echo "... src/tests/affinity.o"
	@echo "... src/tests/affinity.i"
	@echo "... src/tests/affinity.s"
	@echo "... src/tests/benchmark.o"
	@echo "... src/tests/benchmark.i"
	@echo "... src/tests/benchmark.s"
	@echo "... src/tests/code-generator.o"
	@echo "... src/tests/code-generator.i"
	@echo "... src/tests/code-generator.s"
	@echo "... src/tests/tests.o"
	@echo "... src/tests/tests.i"
	@echo "... src/tests/tests.s"
	@echo "... src/virtual_machine.o"
	@echo "... src/virtual_machine.i"
	@echo "... src/virtual_machine.s"
	@echo "... src/virtual_memory.o"
	@echo "... src/virtual_memory.i"
	@echo "... src/virtual_memory.s"
	@echo "... src/vm_compiled.o"
	@echo "... src/vm_compiled.i"
	@echo "... src/vm_compiled.s"
	@echo "... src/vm_compiled_light.o"
	@echo "... src/vm_compiled_light.i"
	@echo "... src/vm_compiled_light.s"
	@echo "... src/vm_interpreted.o"
	@echo "... src/vm_interpreted.i"
	@echo "... src/vm_interpreted.s"
	@echo "... src/vm_interpreted_light.o"
	@echo "... src/vm_interpreted_light.i"
	@echo "... src/vm_interpreted_light.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

